# Generated by Django 5.1.2 on 2025-02-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0003_room_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='logo',
            field=models.ImageField(blank=True, upload_to='roomLogos/'),
        ),
    ]
