# Generated by Django 5.1.2 on 2025-02-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0004_room_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
