# Generated by Django 5.1.2 on 2025-03-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0007_roommember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='roomLogos/'),
        ),
    ]
