# Generated by Django 5.1.2 on 2025-03-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0012_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wsapp.room'),
        ),
    ]
