# Generated by Django 5.1.2 on 2025-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0013_friendship_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.CharField(default='group', max_length=10),
        ),
    ]
